### ISSUE TITLE
Create separate Cake addin to versioning by SemVer

### ISSUE THREAD

**Issue by vCipher** [vCipher/Cake.Hg#8]
It would be better to move versioning functionality to different Cake addin.

**Comment by gep13** [comment]
@vCipher are you familiar with the GitVersion project?  It has been written in such a way, that the Semantic Version asserting can come from anywhere.  In theory, you should be able to slot in using Mercurial to provide the history for the repository, to then assert the version number.  Might be worth looking into, rather than re-inventing the wheel.

**Comment by vCipher** [comment]
@gep13 Yes, I am fimilar with this project. Actually I have just started to write Cake.HgVersion using GitVersion codebase.

**Comment by gep13** [comment]
@vCipher do you think that it would make sense to contribute back to the GitVersion project with the ability to assert the version number of a Hg repository as well?  Rather than creating a separate project?

**Comment by vCipher** [comment]
@gep13 sounds fine, but GitVersion has very strong reference to git and even its name tells us that GitVersion works only with git.

**Comment by gep13** [comment]
Yes, that is true, but names can change 😄 The underlying architecture of GitVersion allows the repository history to come from elsewhere, so technically, there is nothing to stop GitVersion being able to assert a version number from a Hg repository, or an SVN repository, etc.

**Comment by vCipher** [comment]
@gep13 You are right! It can be possible to exctract common codebase and reuse it in GitVersion or in HgVersion and so on.
